title: "CSCI-445: Human Computer Interaction"

outputDir: build
sourceDir: docs

themeDir: theme

customVariables:
  current_year: 2022
  github_edit_url: https://github.com/RK-MSU/CSCI-445-Human-Computer-Interaction/blob/notes/docs/
